# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'creatorscreen.ui'
#
# Created: Thu Sep  3 16:14:52 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(358, 273)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_experimentname = QtGui.QLabel(Dialog)
        self.label_experimentname.setObjectName(_fromUtf8("label_experimentname"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_experimentname)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lineEdit_experimentname = QtGui.QLineEdit(Dialog)
        self.lineEdit_experimentname.setMinimumSize(QtCore.QSize(180, 0))
        self.lineEdit_experimentname.setMaximumSize(QtCore.QSize(180, 16777215))
        self.lineEdit_experimentname.setText(_fromUtf8(""))
        self.lineEdit_experimentname.setMaxLength(100)
        self.lineEdit_experimentname.setObjectName(_fromUtf8("lineEdit_experimentname"))
        self.horizontalLayout_7.addWidget(self.lineEdit_experimentname)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_experimentshortname = QtGui.QLabel(Dialog)
        self.label_experimentshortname.setObjectName(_fromUtf8("label_experimentshortname"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_experimentshortname)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lineEdit_experimentshortname = QtGui.QLineEdit(Dialog)
        self.lineEdit_experimentshortname.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_experimentshortname.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_experimentshortname.setText(_fromUtf8(""))
        self.lineEdit_experimentshortname.setMaxLength(50)
        self.lineEdit_experimentshortname.setObjectName(_fromUtf8("lineEdit_experimentshortname"))
        self.horizontalLayout_6.addWidget(self.lineEdit_experimentshortname)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_experimentmenu = QtGui.QLabel(Dialog)
        self.label_experimentmenu.setObjectName(_fromUtf8("label_experimentmenu"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_experimentmenu)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineEdit_experimentmenu = QtGui.QLineEdit(Dialog)
        self.lineEdit_experimentmenu.setMinimumSize(QtCore.QSize(180, 0))
        self.lineEdit_experimentmenu.setMaximumSize(QtCore.QSize(180, 16777215))
        self.lineEdit_experimentmenu.setText(_fromUtf8(""))
        self.lineEdit_experimentmenu.setMaxLength(100)
        self.lineEdit_experimentmenu.setObjectName(_fromUtf8("lineEdit_experimentmenu"))
        self.horizontalLayout_4.addWidget(self.lineEdit_experimentmenu)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_groupsize = QtGui.QLabel(Dialog)
        self.label_groupsize.setEnabled(True)
        self.label_groupsize.setObjectName(_fromUtf8("label_groupsize"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_groupsize)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.spinBox_groupsize = QtGui.QSpinBox(Dialog)
        self.spinBox_groupsize.setEnabled(True)
        self.spinBox_groupsize.setMinimum(0)
        self.spinBox_groupsize.setMaximum(100)
        self.spinBox_groupsize.setProperty("value", 0)
        self.spinBox_groupsize.setObjectName(_fromUtf8("spinBox_groupsize"))
        self.horizontalLayout_11.addWidget(self.spinBox_groupsize)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.label_groupseachperiod = QtGui.QLabel(Dialog)
        self.label_groupseachperiod.setEnabled(True)
        self.label_groupseachperiod.setObjectName(_fromUtf8("label_groupseachperiod"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_groupseachperiod)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.comboBox_groupseachperiod = QtGui.QComboBox(Dialog)
        self.comboBox_groupseachperiod.setEnabled(True)
        self.comboBox_groupseachperiod.setObjectName(_fromUtf8("comboBox_groupseachperiod"))
        self.horizontalLayout.addWidget(self.comboBox_groupseachperiod)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_periods = QtGui.QLabel(Dialog)
        self.label_periods.setObjectName(_fromUtf8("label_periods"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_periods)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.spinBox_periods = QtGui.QSpinBox(Dialog)
        self.spinBox_periods.setEnabled(True)
        self.spinBox_periods.setMinimum(0)
        self.spinBox_periods.setMaximum(1000)
        self.spinBox_periods.setProperty("value", 0)
        self.spinBox_periods.setObjectName(_fromUtf8("spinBox_periods"))
        self.horizontalLayout_2.addWidget(self.spinBox_periods)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_currency = QtGui.QLabel(Dialog)
        self.label_currency.setObjectName(_fromUtf8("label_currency"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_currency)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lineEdit_currency = QtGui.QLineEdit(Dialog)
        self.lineEdit_currency.setMaximumSize(QtCore.QSize(180, 16777215))
        self.lineEdit_currency.setMaxLength(50)
        self.lineEdit_currency.setObjectName(_fromUtf8("lineEdit_currency"))
        self.horizontalLayout_5.addWidget(self.lineEdit_currency)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.formLayout.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_8.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_8)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Configuration for a new part", None))
        self.label_experimentname.setText(_translate("Dialog", "Experiment name", None))
        self.label_experimentshortname.setText(_translate("Dialog", "Experiment short name", None))
        self.label_experimentmenu.setText(_translate("Dialog", "Menu", None))
        self.label_groupsize.setText(_translate("Dialog", "Group  size", None))
        self.label_groupseachperiod.setText(_translate("Dialog", "Group each period", None))
        self.label_periods.setText(_translate("Dialog", "Number of periods", None))
        self.label_currency.setText(_translate("Dialog", "Experimental currency", None))

