# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'le2mClientGuiSrcQuestFinal.ui'
#
# Created: Thu Feb 19 09:40:50 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(712, 579)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.textEdit = QtGui.QTextEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(600, 70))
        self.textEdit.setMaximumSize(QtCore.QSize(600, 70))
        self.textEdit.setLineWrapMode(QtGui.QTextEdit.WidgetWidth)
        self.textEdit.setLineWrapColumnOrWidth(0)
        self.textEdit.setReadOnly(True)
        self.textEdit.setTabStopWidth(80)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.horizontalLayout_2.addWidget(self.textEdit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_12.addWidget(self.label_16)
        self.spinBox_naissance = QtGui.QSpinBox(Dialog)
        self.spinBox_naissance.setSpecialValueText(_fromUtf8(""))
        self.spinBox_naissance.setPrefix(_fromUtf8(""))
        self.spinBox_naissance.setMinimum(1900)
        self.spinBox_naissance.setMaximum(2100)
        self.spinBox_naissance.setProperty("value", 1900)
        self.spinBox_naissance.setObjectName(_fromUtf8("spinBox_naissance"))
        self.horizontalLayout_12.addWidget(self.spinBox_naissance)
        spacerItem4 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_12.addWidget(self.label_17)
        self.rb_homme = QtGui.QRadioButton(Dialog)
        self.rb_homme.setObjectName(_fromUtf8("rb_homme"))
        self.buttonGroup_6 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_6.setObjectName(_fromUtf8("buttonGroup_6"))
        self.buttonGroup_6.addButton(self.rb_homme)
        self.horizontalLayout_12.addWidget(self.rb_homme)
        self.rb_femme = QtGui.QRadioButton(Dialog)
        self.rb_femme.setObjectName(_fromUtf8("rb_femme"))
        self.buttonGroup_6.addButton(self.rb_femme)
        self.horizontalLayout_12.addWidget(self.rb_femme)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_8.addWidget(self.label_18)
        self.cb_nationalite = QtGui.QComboBox(Dialog)
        self.cb_nationalite.setObjectName(_fromUtf8("cb_nationalite"))
        self.horizontalLayout_8.addWidget(self.cb_nationalite)
        spacerItem6 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.label_19 = QtGui.QLabel(Dialog)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_8.addWidget(self.label_19)
        self.rb_couple_oui = QtGui.QRadioButton(Dialog)
        self.rb_couple_oui.setObjectName(_fromUtf8("rb_couple_oui"))
        self.buttonGroup_4 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_4.setObjectName(_fromUtf8("buttonGroup_4"))
        self.buttonGroup_4.addButton(self.rb_couple_oui)
        self.horizontalLayout_8.addWidget(self.rb_couple_oui)
        self.rb_couple_non = QtGui.QRadioButton(Dialog)
        self.rb_couple_non.setObjectName(_fromUtf8("rb_couple_non"))
        self.buttonGroup_4.addButton(self.rb_couple_non)
        self.horizontalLayout_8.addWidget(self.rb_couple_non)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_20 = QtGui.QLabel(Dialog)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_9.addWidget(self.label_20)
        self.rb_etudiant_oui = QtGui.QRadioButton(Dialog)
        self.rb_etudiant_oui.setObjectName(_fromUtf8("rb_etudiant_oui"))
        self.buttonGroup_5 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_5.setObjectName(_fromUtf8("buttonGroup_5"))
        self.buttonGroup_5.addButton(self.rb_etudiant_oui)
        self.horizontalLayout_9.addWidget(self.rb_etudiant_oui)
        self.rb_etudiant_non = QtGui.QRadioButton(Dialog)
        self.rb_etudiant_non.setObjectName(_fromUtf8("rb_etudiant_non"))
        self.buttonGroup_5.addButton(self.rb_etudiant_non)
        self.horizontalLayout_9.addWidget(self.rb_etudiant_non)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_21 = QtGui.QLabel(Dialog)
        self.label_21.setEnabled(False)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_5.addWidget(self.label_21)
        self.cb_etudiant_discipline = QtGui.QComboBox(Dialog)
        self.cb_etudiant_discipline.setEnabled(False)
        self.cb_etudiant_discipline.setObjectName(_fromUtf8("cb_etudiant_discipline"))
        self.horizontalLayout_5.addWidget(self.cb_etudiant_discipline)
        spacerItem9 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setEnabled(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.cb_etudiant_niveau = QtGui.QComboBox(Dialog)
        self.cb_etudiant_niveau.setEnabled(False)
        self.cb_etudiant_niveau.setObjectName(_fromUtf8("cb_etudiant_niveau"))
        self.horizontalLayout_5.addWidget(self.cb_etudiant_niveau)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_23 = QtGui.QLabel(Dialog)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout.addWidget(self.label_23)
        self.rb_experiences_oui = QtGui.QRadioButton(Dialog)
        self.rb_experiences_oui.setObjectName(_fromUtf8("rb_experiences_oui"))
        self.buttonGroup_7 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_7.setObjectName(_fromUtf8("buttonGroup_7"))
        self.buttonGroup_7.addButton(self.rb_experiences_oui)
        self.horizontalLayout.addWidget(self.rb_experiences_oui)
        self.rb_experiences_non = QtGui.QRadioButton(Dialog)
        self.rb_experiences_non.setObjectName(_fromUtf8("rb_experiences_non"))
        self.buttonGroup_7.addButton(self.rb_experiences_non)
        self.horizontalLayout.addWidget(self.rb_experiences_non)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.spinBox_fratrie_nombre = QtGui.QSpinBox(Dialog)
        self.spinBox_fratrie_nombre.setObjectName(_fromUtf8("spinBox_fratrie_nombre"))
        self.horizontalLayout_3.addWidget(self.spinBox_fratrie_nombre)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_10.addWidget(self.label_3)
        self.spinBox_fratrie_rang = QtGui.QSpinBox(Dialog)
        self.spinBox_fratrie_rang.setObjectName(_fromUtf8("spinBox_fratrie_rang"))
        self.horizontalLayout_10.addWidget(self.spinBox_fratrie_rang)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_13.addWidget(self.label_5)
        self.rb_sportif_oui = QtGui.QRadioButton(Dialog)
        self.rb_sportif_oui.setObjectName(_fromUtf8("rb_sportif_oui"))
        self.buttonGroup = QtGui.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.rb_sportif_oui)
        self.horizontalLayout_13.addWidget(self.rb_sportif_oui)
        self.rb_sportif_non = QtGui.QRadioButton(Dialog)
        self.rb_sportif_non.setObjectName(_fromUtf8("rb_sportif_non"))
        self.buttonGroup.addButton(self.rb_sportif_non)
        self.horizontalLayout_13.addWidget(self.rb_sportif_non)
        spacerItem14 = QtGui.QSpacerItem(75, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem14)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setEnabled(False)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_16.addWidget(self.label_8)
        self.rb_sportif_collectif = QtGui.QRadioButton(Dialog)
        self.rb_sportif_collectif.setEnabled(False)
        self.rb_sportif_collectif.setObjectName(_fromUtf8("rb_sportif_collectif"))
        self.buttonGroup_2 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.rb_sportif_collectif)
        self.horizontalLayout_16.addWidget(self.rb_sportif_collectif)
        self.rb_sportif_individuel = QtGui.QRadioButton(Dialog)
        self.rb_sportif_individuel.setEnabled(False)
        self.rb_sportif_individuel.setObjectName(_fromUtf8("rb_sportif_individuel"))
        self.buttonGroup_2.addButton(self.rb_sportif_individuel)
        self.horizontalLayout_16.addWidget(self.rb_sportif_individuel)
        spacerItem15 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem15)
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setEnabled(False)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_16.addWidget(self.label_9)
        self.rb_sportif_competition_oui = QtGui.QRadioButton(Dialog)
        self.rb_sportif_competition_oui.setEnabled(False)
        self.rb_sportif_competition_oui.setObjectName(_fromUtf8("rb_sportif_competition_oui"))
        self.buttonGroup_3 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_3.setObjectName(_fromUtf8("buttonGroup_3"))
        self.buttonGroup_3.addButton(self.rb_sportif_competition_oui)
        self.horizontalLayout_16.addWidget(self.rb_sportif_competition_oui)
        self.rb_sportif_competition_non = QtGui.QRadioButton(Dialog)
        self.rb_sportif_competition_non.setEnabled(False)
        self.rb_sportif_competition_non.setObjectName(_fromUtf8("rb_sportif_competition_non"))
        self.buttonGroup_3.addButton(self.rb_sportif_competition_non)
        self.horizontalLayout_16.addWidget(self.rb_sportif_competition_non)
        spacerItem16 = QtGui.QSpacerItem(59, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem16)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem17 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem17)
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setEnabled(False)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_17.addWidget(self.label_10)
        self.cb_sportif_competition_niveau = QtGui.QComboBox(Dialog)
        self.cb_sportif_competition_niveau.setEnabled(False)
        self.cb_sportif_competition_niveau.setObjectName(_fromUtf8("cb_sportif_competition_niveau"))
        self.cb_sportif_competition_niveau.addItem(_fromUtf8(""))
        self.cb_sportif_competition_niveau.addItem(_fromUtf8(""))
        self.cb_sportif_competition_niveau.addItem(_fromUtf8(""))
        self.cb_sportif_competition_niveau.addItem(_fromUtf8(""))
        self.cb_sportif_competition_niveau.addItem(_fromUtf8(""))
        self.horizontalLayout_17.addWidget(self.cb_sportif_competition_niveau)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem18)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_4.addWidget(self.label_11)
        self.cb_religion_place = QtGui.QComboBox(Dialog)
        self.cb_religion_place.setObjectName(_fromUtf8("cb_religion_place"))
        self.cb_religion_place.addItem(_fromUtf8(""))
        self.cb_religion_place.addItem(_fromUtf8(""))
        self.cb_religion_place.addItem(_fromUtf8(""))
        self.cb_religion_place.addItem(_fromUtf8(""))
        self.cb_religion_place.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.cb_religion_place)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem19)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_6.addWidget(self.label_15)
        self.cb_religion_nom = QtGui.QComboBox(Dialog)
        self.cb_religion_nom.setObjectName(_fromUtf8("cb_religion_nom"))
        self.cb_religion_nom.addItem(_fromUtf8(""))
        self.cb_religion_nom.addItem(_fromUtf8(""))
        self.cb_religion_nom.addItem(_fromUtf8(""))
        self.cb_religion_nom.addItem(_fromUtf8(""))
        self.cb_religion_nom.addItem(_fromUtf8(""))
        self.cb_religion_nom.addItem(_fromUtf8(""))
        self.cb_religion_nom.addItem(_fromUtf8(""))
        self.cb_religion_nom.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.cb_religion_nom)
        spacerItem20 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem20)
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_6.addWidget(self.label_12)
        self.cb_religion_croyance = QtGui.QComboBox(Dialog)
        self.cb_religion_croyance.setObjectName(_fromUtf8("cb_religion_croyance"))
        self.cb_religion_croyance.addItem(_fromUtf8(""))
        self.cb_religion_croyance.addItem(_fromUtf8(""))
        self.cb_religion_croyance.addItem(_fromUtf8(""))
        self.cb_religion_croyance.addItem(_fromUtf8(""))
        self.cb_religion_croyance.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.cb_religion_croyance)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem21)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem22)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        spacerItem23 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem23)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem24)
        self.pushButton_valider = QtGui.QPushButton(Dialog)
        self.pushButton_valider.setObjectName(_fromUtf8("pushButton_valider"))
        self.horizontalLayout_11.addWidget(self.pushButton_valider)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        spacerItem25 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem25)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.rb_etudiant_oui, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_21.setEnabled)
        QtCore.QObject.connect(self.rb_etudiant_oui, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cb_etudiant_discipline.setEnabled)
        QtCore.QObject.connect(self.rb_etudiant_oui, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_2.setEnabled)
        QtCore.QObject.connect(self.rb_etudiant_oui, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cb_etudiant_niveau.setEnabled)
        QtCore.QObject.connect(self.rb_sportif_oui, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_8.setEnabled)
        QtCore.QObject.connect(self.rb_sportif_oui, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.rb_sportif_collectif.setEnabled)
        QtCore.QObject.connect(self.rb_sportif_oui, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.rb_sportif_individuel.setEnabled)
        QtCore.QObject.connect(self.rb_sportif_oui, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_9.setEnabled)
        QtCore.QObject.connect(self.rb_sportif_oui, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.rb_sportif_competition_oui.setEnabled)
        QtCore.QObject.connect(self.rb_sportif_oui, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.rb_sportif_competition_non.setEnabled)
        QtCore.QObject.connect(self.rb_sportif_competition_oui, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_10.setEnabled)
        QtCore.QObject.connect(self.rb_sportif_competition_oui, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cb_sportif_competition_niveau.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Questionnaire final", None))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Veuillez remplir le questionnaire ci-dessous. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ce questionnaire est totalement anonyme, merci d\'y répondre avec sincérité.</p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.label_16.setText(_translate("Dialog", "Année de naissance (yyyy) ", None))
        self.label_17.setText(_translate("Dialog", "Sexe ", None))
        self.rb_homme.setText(_translate("Dialog", "Homme", None))
        self.rb_femme.setText(_translate("Dialog", "Femme", None))
        self.label_18.setText(_translate("Dialog", "Nationalité ", None))
        self.label_19.setText(_translate("Dialog", "Vivez-vous en couple ? ", None))
        self.rb_couple_oui.setText(_translate("Dialog", "Oui", None))
        self.rb_couple_non.setText(_translate("Dialog", "Non", None))
        self.label_20.setText(_translate("Dialog", "Etes-vous étudiant(e) ? ", None))
        self.rb_etudiant_oui.setText(_translate("Dialog", "Oui", None))
        self.rb_etudiant_non.setText(_translate("Dialog", "Non", None))
        self.label_21.setText(_translate("Dialog", "Discipline étudiée ", None))
        self.label_2.setText(_translate("Dialog", "Année d\'étude", None))
        self.label_23.setText(_translate("Dialog", "Avez-vous déjà participé à une expérience d\'économie ? ", None))
        self.rb_experiences_oui.setText(_translate("Dialog", "Oui", None))
        self.rb_experiences_non.setText(_translate("Dialog", "Non", None))
        self.label.setText(_translate("Dialog", "Combien avez-vous de frères et soeurs (demi compris)?", None))
        self.label_3.setText(_translate("Dialog", "Votre rang parmi vos frères et soeurs", None))
        self.label_5.setText(_translate("Dialog", "Pratiquez-vous un sport ? ", None))
        self.rb_sportif_oui.setText(_translate("Dialog", "Oui", None))
        self.rb_sportif_non.setText(_translate("Dialog", "Non", None))
        self.label_8.setText(_translate("Dialog", "Type de sport ", None))
        self.rb_sportif_collectif.setText(_translate("Dialog", "Collectif", None))
        self.rb_sportif_individuel.setText(_translate("Dialog", "Individuel", None))
        self.label_9.setText(_translate("Dialog", "Faites-vous de la compétition ?", None))
        self.rb_sportif_competition_oui.setText(_translate("Dialog", "Oui", None))
        self.rb_sportif_competition_non.setText(_translate("Dialog", "Non", None))
        self.label_10.setText(_translate("Dialog", "A quel niveau ? ", None))
        self.cb_sportif_competition_niveau.setItemText(0, _translate("Dialog", "Choisir", None))
        self.cb_sportif_competition_niveau.setItemText(1, _translate("Dialog", "Départemental", None))
        self.cb_sportif_competition_niveau.setItemText(2, _translate("Dialog", "Régional", None))
        self.cb_sportif_competition_niveau.setItemText(3, _translate("Dialog", "National", None))
        self.cb_sportif_competition_niveau.setItemText(4, _translate("Dialog", "International", None))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p>Est ce que la religion tient une place importante dans votre vie ?</p></body></html>", None))
        self.cb_religion_place.setItemText(0, _translate("Dialog", "Choisir", None))
        self.cb_religion_place.setItemText(1, _translate("Dialog", "Trés importante", None))
        self.cb_religion_place.setItemText(2, _translate("Dialog", "Assez importante", None))
        self.cb_religion_place.setItemText(3, _translate("Dialog", "Peu importante", None))
        self.cb_religion_place.setItemText(4, _translate("Dialog", "Pas du tout importante", None))
        self.label_15.setText(_translate("Dialog", "Quelle est votre religion ?", None))
        self.cb_religion_nom.setItemText(0, _translate("Dialog", "Choisir", None))
        self.cb_religion_nom.setItemText(1, _translate("Dialog", "Bouddhiste", None))
        self.cb_religion_nom.setItemText(2, _translate("Dialog", "Catholique", None))
        self.cb_religion_nom.setItemText(3, _translate("Dialog", "Juif", None))
        self.cb_religion_nom.setItemText(4, _translate("Dialog", "Musulman", None))
        self.cb_religion_nom.setItemText(5, _translate("Dialog", "Protestant", None))
        self.cb_religion_nom.setItemText(6, _translate("Dialog", "Autre", None))
        self.cb_religion_nom.setItemText(7, _translate("Dialog", "Aucune", None))
        self.label_12.setText(_translate("Dialog", "En général diriez-vous que vous êtes ", None))
        self.cb_religion_croyance.setItemText(0, _translate("Dialog", "Choisir", None))
        self.cb_religion_croyance.setItemText(1, _translate("Dialog", "Trés croyant(e)", None))
        self.cb_religion_croyance.setItemText(2, _translate("Dialog", "Assez croyant(e)", None))
        self.cb_religion_croyance.setItemText(3, _translate("Dialog", "Peu croyant(e)", None))
        self.cb_religion_croyance.setItemText(4, _translate("Dialog", "Non croyant(e)", None))
        self.pushButton_valider.setText(_translate("Dialog", "Ok", None))

