# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'le2mServGuiSrcQuestionCompEdit.ui'
#
# Created: Tue Sep 16 15:10:16 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(800, 611)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_question = QtGui.QHBoxLayout()
        self.horizontalLayout_question.setObjectName(_fromUtf8("horizontalLayout_question"))
        self.label_5 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_question.addWidget(self.label_5)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_question.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_question)
        self.horizontalLayout_numero = QtGui.QHBoxLayout()
        self.horizontalLayout_numero.setObjectName(_fromUtf8("horizontalLayout_numero"))
        self.label_numero = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_numero.setFont(font)
        self.label_numero.setObjectName(_fromUtf8("label_numero"))
        self.horizontalLayout_numero.addWidget(self.label_numero)
        self.spinBox_numero = QtGui.QSpinBox(Dialog)
        self.spinBox_numero.setObjectName(_fromUtf8("spinBox_numero"))
        self.horizontalLayout_numero.addWidget(self.spinBox_numero)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_numero.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_numero)
        self.verticalLayout_ennonce = QtGui.QVBoxLayout()
        self.verticalLayout_ennonce.setObjectName(_fromUtf8("verticalLayout_ennonce"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_ennonce = QtGui.QLabel(Dialog)
        self.label_ennonce.setObjectName(_fromUtf8("label_ennonce"))
        self.horizontalLayout_2.addWidget(self.label_ennonce)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_ennonce.addLayout(self.horizontalLayout_2)
        self.textEdit_ennonce = QtGui.QTextEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_ennonce.sizePolicy().hasHeightForWidth())
        self.textEdit_ennonce.setSizePolicy(sizePolicy)
        self.textEdit_ennonce.setMinimumSize(QtCore.QSize(600, 0))
        self.textEdit_ennonce.setMaximumSize(QtCore.QSize(16777215, 150))
        self.textEdit_ennonce.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_ennonce.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_ennonce.setObjectName(_fromUtf8("textEdit_ennonce"))
        self.verticalLayout_ennonce.addWidget(self.textEdit_ennonce)
        self.verticalLayout.addLayout(self.verticalLayout_ennonce)
        self.verticalLayout_propositions = QtGui.QVBoxLayout()
        self.verticalLayout_propositions.setObjectName(_fromUtf8("verticalLayout_propositions"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_propositions = QtGui.QLabel(Dialog)
        self.label_propositions.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_propositions.setObjectName(_fromUtf8("label_propositions"))
        self.horizontalLayout_11.addWidget(self.label_propositions)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_propositions.addLayout(self.horizontalLayout_11)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.lineEdit_propositions_1 = QtGui.QLineEdit(Dialog)
        self.lineEdit_propositions_1.setObjectName(_fromUtf8("lineEdit_propositions_1"))
        self.horizontalLayout_5.addWidget(self.lineEdit_propositions_1)
        self.checkBox_propositions_1 = QtGui.QCheckBox(Dialog)
        self.checkBox_propositions_1.setObjectName(_fromUtf8("checkBox_propositions_1"))
        self.horizontalLayout_5.addWidget(self.checkBox_propositions_1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEdit_propositions_2 = QtGui.QLineEdit(Dialog)
        self.lineEdit_propositions_2.setObjectName(_fromUtf8("lineEdit_propositions_2"))
        self.horizontalLayout_4.addWidget(self.lineEdit_propositions_2)
        self.checkBox_propositions_2 = QtGui.QCheckBox(Dialog)
        self.checkBox_propositions_2.setObjectName(_fromUtf8("checkBox_propositions_2"))
        self.horizontalLayout_4.addWidget(self.checkBox_propositions_2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_propositions.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.lineEdit_propositions_3 = QtGui.QLineEdit(Dialog)
        self.lineEdit_propositions_3.setObjectName(_fromUtf8("lineEdit_propositions_3"))
        self.horizontalLayout_6.addWidget(self.lineEdit_propositions_3)
        self.checkBox_propositions_3 = QtGui.QCheckBox(Dialog)
        self.checkBox_propositions_3.setObjectName(_fromUtf8("checkBox_propositions_3"))
        self.horizontalLayout_6.addWidget(self.checkBox_propositions_3)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.lineEdit_propositions_4 = QtGui.QLineEdit(Dialog)
        self.lineEdit_propositions_4.setObjectName(_fromUtf8("lineEdit_propositions_4"))
        self.horizontalLayout_7.addWidget(self.lineEdit_propositions_4)
        self.checkBox_propositions_4 = QtGui.QCheckBox(Dialog)
        self.checkBox_propositions_4.setObjectName(_fromUtf8("checkBox_propositions_4"))
        self.horizontalLayout_7.addWidget(self.checkBox_propositions_4)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_propositions.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.lineEdit_propositions_5 = QtGui.QLineEdit(Dialog)
        self.lineEdit_propositions_5.setObjectName(_fromUtf8("lineEdit_propositions_5"))
        self.horizontalLayout_8.addWidget(self.lineEdit_propositions_5)
        self.checkBox_propositions_5 = QtGui.QCheckBox(Dialog)
        self.checkBox_propositions_5.setObjectName(_fromUtf8("checkBox_propositions_5"))
        self.horizontalLayout_8.addWidget(self.checkBox_propositions_5)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_10.addWidget(self.label_8)
        self.lineEdit_propositions_6 = QtGui.QLineEdit(Dialog)
        self.lineEdit_propositions_6.setEnabled(True)
        self.lineEdit_propositions_6.setObjectName(_fromUtf8("lineEdit_propositions_6"))
        self.horizontalLayout_10.addWidget(self.lineEdit_propositions_6)
        self.checkBox_propositions_6 = QtGui.QCheckBox(Dialog)
        self.checkBox_propositions_6.setEnabled(True)
        self.checkBox_propositions_6.setObjectName(_fromUtf8("checkBox_propositions_6"))
        self.horizontalLayout_10.addWidget(self.checkBox_propositions_6)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.verticalLayout_propositions.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addLayout(self.verticalLayout_propositions)
        self.verticalLayout_explication = QtGui.QVBoxLayout()
        self.verticalLayout_explication.setObjectName(_fromUtf8("verticalLayout_explication"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_13.addWidget(self.label_4)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.verticalLayout_explication.addLayout(self.horizontalLayout_13)
        self.textEdit_explication = QtGui.QTextEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_explication.sizePolicy().hasHeightForWidth())
        self.textEdit_explication.setSizePolicy(sizePolicy)
        self.textEdit_explication.setMinimumSize(QtCore.QSize(600, 0))
        self.textEdit_explication.setMaximumSize(QtCore.QSize(16777215, 150))
        self.textEdit_explication.setLineWrapMode(QtGui.QTextEdit.WidgetWidth)
        self.textEdit_explication.setObjectName(_fromUtf8("textEdit_explication"))
        self.verticalLayout_explication.addWidget(self.textEdit_explication)
        self.verticalLayout.addLayout(self.verticalLayout_explication)
        self.horizontalLayout_valider = QtGui.QHBoxLayout()
        self.horizontalLayout_valider.setObjectName(_fromUtf8("horizontalLayout_valider"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_valider.addItem(spacerItem11)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_valider.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_valider)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Question de compréhension", None))
        self.label_5.setText(_translate("Dialog", "Question de compréhension", None))
        self.label_numero.setText(_translate("Dialog", "Numéro:", None))
        self.label_ennonce.setText(_translate("Dialog", "Ennoncé:", None))
        self.label_propositions.setText(_translate("Dialog", "Propositions (dans l\'ordre des numéros):", None))
        self.label.setText(_translate("Dialog", "1.", None))
        self.checkBox_propositions_1.setText(_translate("Dialog", "Cliquer si c\'est une bonne réponse", None))
        self.label_2.setText(_translate("Dialog", "2.", None))
        self.checkBox_propositions_2.setText(_translate("Dialog", "Cliquer si c\'est une bonne réponse", None))
        self.label_3.setText(_translate("Dialog", "3.", None))
        self.checkBox_propositions_3.setText(_translate("Dialog", "Cliquer si c\'est une bonne réponse", None))
        self.label_6.setText(_translate("Dialog", "4.", None))
        self.checkBox_propositions_4.setText(_translate("Dialog", "Cliquer si c\'est une bonne réponse", None))
        self.label_7.setText(_translate("Dialog", "5.", None))
        self.checkBox_propositions_5.setText(_translate("Dialog", "Cliquer si c\'est une bonne réponse", None))
        self.label_8.setText(_translate("Dialog", "6.", None))
        self.checkBox_propositions_6.setText(_translate("Dialog", "Cliquer si c\'est une bonne réponse", None))
        self.label_4.setText(_translate("Dialog", "Explication:", None))

