# -*- coding: utf-8 -*-

# variables
BASELINE = 0
TREATMENTS_NAMES = {BASELINE: "baseline"}

# parameters
TREATMENT = BASELINE
DOTATION = 20
RENDEMENT_INDIV = 1
RENDEMENT_COLL = 0.5
# MPCR = 0.5
TAUX_CONVERSION = 0.04
NOMBRE_PERIODES = 10
TAILLE_GROUPES = 4
GROUPES_CHAQUE_PERIODE = False
PERIODE_ESSAI = False
MONNAIE = u"ecu"

# DECISION
DECISION_MIN = 0
DECISION_MAX = DOTATION
DECISION_STEP = 1

