# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'le2mServGuiSrcMain.ui'
#
# Created: Fri Sep 11 22:31:49 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EcranServeur(object):
    def setupUi(self, EcranServeur):
        EcranServeur.setObjectName(_fromUtf8("EcranServeur"))
        EcranServeur.resize(1008, 722)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EcranServeur.sizePolicy().hasHeightForWidth())
        EcranServeur.setSizePolicy(sizePolicy)
        EcranServeur.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtGui.QWidget(EcranServeur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.onglets = QtGui.QTabWidget(self.centralwidget)
        self.onglets.setObjectName(_fromUtf8("onglets"))
        self.tabInfos = QtGui.QWidget()
        self.tabInfos.setObjectName(_fromUtf8("tabInfos"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabInfos)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_le2m = QtGui.QLabel(self.tabInfos)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_le2m.setFont(font)
        self.label_le2m.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.label_le2m.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_le2m.setObjectName(_fromUtf8("label_le2m"))
        self.horizontalLayout_6.addWidget(self.label_le2m)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label_logo_laboratoire = QtGui.QLabel(self.tabInfos)
        self.label_logo_laboratoire.setText(_fromUtf8(""))
        self.label_logo_laboratoire.setPixmap(QtGui.QPixmap(_fromUtf8("../../../img/logo_lameta.gif")))
        self.label_logo_laboratoire.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo_laboratoire.setObjectName(_fromUtf8("label_logo_laboratoire"))
        self.horizontalLayout_6.addWidget(self.label_logo_laboratoire)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_image_centre = QtGui.QLabel(self.tabInfos)
        self.label_image_centre.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 255);"))
        self.label_image_centre.setFrameShadow(QtGui.QFrame.Raised)
        self.label_image_centre.setLineWidth(5)
        self.label_image_centre.setText(_fromUtf8(""))
        self.label_image_centre.setPixmap(QtGui.QPixmap(_fromUtf8("../../../img/mix.jpg")))
        self.label_image_centre.setObjectName(_fromUtf8("label_image_centre"))
        self.horizontalLayout_3.addWidget(self.label_image_centre)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_infos_serveur = QtGui.QLabel(self.tabInfos)
        self.label_infos_serveur.setObjectName(_fromUtf8("label_infos_serveur"))
        self.horizontalLayout_2.addWidget(self.label_infos_serveur)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.onglets.addTab(self.tabInfos, _fromUtf8(""))
        self.tabClients = QtGui.QWidget()
        self.tabClients.setObjectName(_fromUtf8("tabClients"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabClients)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_connectedremotes = QtGui.QLabel(self.tabClients)
        self.label_connectedremotes.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_connectedremotes.setObjectName(_fromUtf8("label_connectedremotes"))
        self.horizontalLayout.addWidget(self.label_connectedremotes)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tv_clients_connectes = QtGui.QTableView(self.tabClients)
        self.tv_clients_connectes.setMinimumSize(QtCore.QSize(850, 500))
        self.tv_clients_connectes.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tv_clients_connectes.setObjectName(_fromUtf8("tv_clients_connectes"))
        self.horizontalLayout_5.addWidget(self.tv_clients_connectes)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.onglets.addTab(self.tabClients, _fromUtf8(""))
        self.tabExperience = QtGui.QWidget()
        self.tabExperience.setObjectName(_fromUtf8("tabExperience"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabExperience)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lbl_expe_serveur = QtGui.QLabel(self.tabExperience)
        self.lbl_expe_serveur.setObjectName(_fromUtf8("lbl_expe_serveur"))
        self.gridLayout_3.addWidget(self.lbl_expe_serveur, 0, 0, 1, 1)
        self.lbl_expe_clients = QtGui.QLabel(self.tabExperience)
        self.lbl_expe_clients.setObjectName(_fromUtf8("lbl_expe_clients"))
        self.gridLayout_3.addWidget(self.lbl_expe_clients, 0, 1, 1, 1)
        self.list_server = QtGui.QListWidget(self.tabExperience)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_server.sizePolicy().hasHeightForWidth())
        self.list_server.setSizePolicy(sizePolicy)
        self.list_server.setMinimumSize(QtCore.QSize(350, 500))
        self.list_server.setObjectName(_fromUtf8("list_server"))
        self.gridLayout_3.addWidget(self.list_server, 1, 0, 1, 1)
        self.listWidget_attente = QtGui.QListWidget(self.tabExperience)
        self.listWidget_attente.setMinimumSize(QtCore.QSize(150, 500))
        self.listWidget_attente.setMaximumSize(QtCore.QSize(250, 16777215))
        self.listWidget_attente.setObjectName(_fromUtf8("listWidget_attente"))
        self.gridLayout_3.addWidget(self.listWidget_attente, 1, 2, 1, 1)
        self.list_client = QtGui.QListWidget(self.tabExperience)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_client.sizePolicy().hasHeightForWidth())
        self.list_client.setSizePolicy(sizePolicy)
        self.list_client.setMinimumSize(QtCore.QSize(350, 500))
        self.list_client.setObjectName(_fromUtf8("list_client"))
        self.gridLayout_3.addWidget(self.list_client, 1, 1, 1, 1)
        self.label_attente = QtGui.QLabel(self.tabExperience)
        self.label_attente.setObjectName(_fromUtf8("label_attente"))
        self.gridLayout_3.addWidget(self.label_attente, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.onglets.addTab(self.tabExperience, _fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.onglets)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        EcranServeur.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(EcranServeur)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1008, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        EcranServeur.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(EcranServeur)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        EcranServeur.setStatusBar(self.statusbar)

        self.retranslateUi(EcranServeur)
        self.onglets.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(EcranServeur)

    def retranslateUi(self, EcranServeur):
        EcranServeur.setWindowTitle(_translate("EcranServeur", "Serveur", None))
        self.label_le2m.setText(_translate("EcranServeur", "LE2M - Logiciel pour les Expériences d\'Economie de Montpellier", None))
        self.label_infos_serveur.setText(_translate("EcranServeur", "TextLabel", None))
        self.onglets.setTabText(self.onglets.indexOf(self.tabInfos), _translate("EcranServeur", "Informations serveur", None))
        self.label_connectedremotes.setText(_translate("EcranServeur", "Clients connectés:", None))
        self.onglets.setTabText(self.onglets.indexOf(self.tabClients), _translate("EcranServeur", "Gestion des clients", None))
        self.lbl_expe_serveur.setText(_translate("EcranServeur", "Serveur", None))
        self.lbl_expe_clients.setText(_translate("EcranServeur", "Clients", None))
        self.label_attente.setText(_translate("EcranServeur", "Décision", None))
        self.onglets.setTabText(self.onglets.indexOf(self.tabExperience), _translate("EcranServeur", "Suivi de l\'expérience", None))
