# -*- coding: utf-8 -*-

# VARIABLES ====================================================================
BASELINE = 0
CARTONS_LOCAL_AUTRE = 1
CARTONS_LOCAL = 2
CARTONS_GLOBAL = 3
CARTONS_LOCAL_GLOBAL = 4
SANS_COMMUNICATION = 0
COMMUNICATION_LOCAL = 1
COMMUNICATION_GLOBAL = 2

# PARAMETRES ===================================================================
TRAITEMENT = BASELINE
COMMUNICATION = SANS_COMMUNICATION
DOTATION = 20
FACTEUR_COMPTE_LOCAL = 0.4
FACTEUR_COMPTE_GLOBAL = 0.4
TAUX_CONVERSION = 0.025
NOMBRE_PERIODES = 10 
# attention, pas plus de 2 sous-groupe dans un groupe sinon pb dans prog
TAILLE_GROUPES = 4
TAILLE_SOUS_GROUPES = 2
DOTATION_CARTONS = 10
MONNAIE = u"ecu"
COMMUNICATION_TEMPS = 120
COMMUNICATION_PERIODES = [1]

# GRAPHIQUE ====================================================================
INDIVIDUEL_MIN = 0
INDIVIDUEL_MAX = DOTATION
INDIVIDUEL_STEP = 1
LOCAL_MIN = 0
LOCAL_MAX = DOTATION
LOCAL_STEP = 1
GLOBAL_MIN = 0
GLOBAL_MAX = DOTATION
GLOBAL_STEP = 1
CARTONS_MIN = 0
CARTONS_MAX = DOTATION_CARTONS
CARTONS_STEP = 1
